### HTTP test file (https://www.jetbrains.com/help/idea/exploring-http-syntax.html)
#
# NOTE: Usage (for nvim):
# - install luarocks and lua-5.1/lua5.1/compat-lua (via package manager)
# - install rest.nvim plugin 
# - hover cursor on a request you want to run and :Rest run
#

### get all post
GET http://localhost:3000/post/all

### register
POST http://api.zel.kim/user/register
Content-Type: application/json 

{
    "credentials": {
        "email": "w2helloworld@dlsu.edu.ph",
        "password": "12345678@Aa"
    }
}

### setup
POST http://api.zel.kim/user/setup
Content-Type: application/json
Authorization: Bearer <insert-token>

{
    "info": {
        "name": {
            "first": "w2helloworld",
            "last": "YES"
        },
        "username": "@w2helloworld",
        "batchid": "123",
        "program": "BSIT"
    }
}

### login
POST http://api.zel.kim/user/login
Content-Type: application/json

{
    "credentials": {
        "email": "w2helloworld@dlsu.edu.ph",
        "password": "12345678@Aa"
    }
}
